WITH CAR_CONDITION AS (
    SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE, C.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR AS A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C ON A.CAR_TYPE = C.CAR_TYPE
    WHERE A.CAR_TYPE IN ('세단', 'SUV') AND
        C.DURATION_TYPE = '30일 이상'
)

SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * 30) AS FEE
FROM CAR_CONDITION
WHERE DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * 30 BETWEEN 500000 AND 2000000 AND
    CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC