WITH TOTAL AS (
    SELECT COUNT(*) AS CNT
    FROM USER_INFO
    WHERE JOINED LIKE "2021%"
)

SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, 
        COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
        ROUND(COUNT(DISTINCT S.USER_ID) / T.CNT, 1) AS PURCHASED_RATIO
FROM USER_INFO U
JOIN ONLINE_SALE S ON U.USER_ID = S.USER_ID,
     TOTAL T
WHERE U.JOINED LIKE "2021%"
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH