
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER AS O
JOIN FOOD_PRODUCT AS P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE PRODUCE_DATE IN (
    SELECT PRODUCE_DATE
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
)
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID